# Generated by Django 4.2.10 on 2024-05-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_pgtrgm'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.book')),
                ('data', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='borrowed_book',
        ),
        migrations.AddField(
            model_name='student',
            name='borrow_records',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.borrowrecord'),
        ),
    ]
