# Generated by Django 4.2.10 on 2024-05-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_borrowrecord_remove_student_borrowed_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='data',
            new_name='return_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='borrow_records',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
