# Generated by Django 4.2.10 on 2024-05-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_data_borrowrecord_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
