# Generated by Django 4.2.10 on 2024-05-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_copies'),
        ('users', '0004_remove_borrowrecord_is_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.book'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
